### ISSUE TITLE
Dimmer minimum value '1%'

### ISSUE THREAD

**Issue by DonBosserez** [Tiemooowh/homeassistant-teletask#2]
Hi Tiemoowh,

First of all, great work, love this integration!

Question for you, when using the dimmers in Home Assistant I noticed that the minimum Dimmer value is 1% instead of 0% is there any way we can change this?

The 1% is not an issue for the dimmers or lights as I'm pretty sure we are already picking up a noise level greater than 100mV on the 0-10 dimmer lines, but is an issue for the LED feedback function in the Teletask Aurus touch panels.. Whenever I use my dimmers through HA the feedback LED's of my switches are all 'ON' as for the DoIP unit 1% != OFF. I already tried adding an automation that sets the light to OFF when my input number goes to 1 (or 0) but I'm still having 1% in Prosoft and feedback LED's on. Thanks in advance!

**Comment by Tiemooowh** [comment]
Latest version in HACS now turns 1 into 0 ;-)
