### ISSUE TITLE
Newbee

### ISSUE THREAD

**Issue by bertca** [Tiemooowh/homeassistant-teletask#4]
Hi Tiemoowh,
I'm pretty new here. But I want to thank you for your work.
I have a teletask installation for about 15 years now, and I'm reaching the edges of what is possible with it. Last year I started with Home Assistant and was looking for a way to control Teletask with it. At that point your work was not available yet so I tried to get voice control and Google Home as a workaround. I never managed to get it working as there are too many in-betweens. So I gave up...
Last week I found your repository by accident, tried it out and it seems to work pretty well.
My 2 main projects with it are:
1. create a "follow-the-sun" so my blinds/shutters go up/down when the sun is shining on them. That way I can keep it cooler inside my home. With Teletask I can use a Timed Local Mood but this goes with fixed time intervals. With HA I will be able to use sunset time and even weather reports... Yeeha!
2. 15 years ago, we decided to have 1 thermostat on the upper floor (5 bedrooms). Now the kids grew up, I want a thermostat in every room to control the separate temperatures. Not easy to do this with Teletask as third party stuff can't be implemented. But with HA I can install smart valves and thanks to your work, I can integrate it in Teletask. Yeeha again!

So in fact, I just want to thank you for the job done, and I'm always willing to test new features if needed...

May one little question. I'm using the Teletask test license for the moment. The license itself is rather pricy. Do you know where I can get it cheaper, or is Teletask the only place to buy?

Regards,

Bert

**Comment by Tiemooowh** [comment]
Hey Bert,

Sorry for the late response.
First of all, thanks for the appreciation! ;-)

Unfortunately the price is what it is, I'm afraid. I bought it through a
Teletask dealer, yet it costs some money to open it up.
For Home Control systems nowadays I think this should be the standard, but
probably you've already paid for that "open license" during the order of
the Central Control Unit ;-)

Best regards,
T

**Comment by bertca** [comment]
Hi Tiemooowh,
I bought the license. I see it as an investment and as a hobby - that way the price doesn't feel that high :-)

The heating part is already up and running - the Teletask thermostat has been by-passed. Yes!
Light switches is straight forward - so no problem for this.
But now I'm looking at the dimmers. I have 4 dimmers in my Teletask Output Dimmer list (see picture). I noticed in your documentation that you give them a 'relay' address and a 'brightness address'. But in my opinion Teletask has a separate Relay list and Dimmer list. So my dimmers do not have a relay address... Am I missing something here, or is my setup not compatible? I can make a workaround with a local mood, but then I won't be able to use the dim function...
Could you give me thoughts about this?

Thanks,

Bert
![Knipsel](https://user-images.githubusercontent.com/79922139/155685708-984b1a10-f241-40f5-8a03-fb14d0a77175.JPG)

**Comment by Tiemooowh** [comment]
Hey Bert!!

Wonderful! Glad things are working out! ( I was on holiday last couple of
days and tried to stay away as far as possible from a computer ;-))

In my setup I had created a topology (on a recommandation of the
electrician) to separate on and off from dimming capabilities, thus that's
why the dimming channel is bundled with another component (in my case with
a RELAY). I think you can manage it by creating a "FLAG" (which could act
as a dummy relay).

Let me know if this would work out for you? I'll try to create some time to
update both HASS plugin and Python Lib somewhere this month ;-)

Br
T

**Comment by bertca** [comment]
Tiemoowh,

 

I created a locmood as switch. I can turn the dimmers on/off at a level defined by the locmood (a fix value). No dimming anymore…

 

But I’m still a little bit confused. Can you explain me your setup in detail? Do you have a physical teletask dimmer module connected to your teletask central unit/ autobus (as shown in the picture in my previous mail)?

I do not see the sense of a dummy flag in Teletask – as it’s not connected to something… 

I tried your setup with a non-existing relay address and with a flag I created. But none of them do anything to the lights…

Unfortunately I don’t know anything about python (yet) to have a look myself… So I have to count on your knowledge. 😉 But I’m always willing to dummy test your changes.

 

 

 - doip_component: relay

    address: "31"

    brightness_address: "1"

    name: "Led Strip Bedroom 1"

 

Bert
