### ISSUE TITLE
Lights issue

### ISSUE THREAD

**Issue by tomdevos2401** [Tiemooowh/homeassistant-teletask#6]
Hi,

I started to configure your nice piece of work. Most things work well, with some errors.

Logger: teletask.log
Source: /usr/local/lib/python3.9/site-packages/teletask/core/telegram_queue.py:119 
First occurred: 18:22:28 (4 occurrences) 
Last logged: 18:22:28

No TeletaskIP Callback not defined That was no valid number. Try again...

And 

This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/teletask/light.py:76 
Integration: Teletask 
First occurred: 18:47:10 (2 occurrences) 
Last logged: 18:47:18

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 740, in _update_entity_states
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 520, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 573, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 968, in state_attributes
    data[ATTR_BRIGHTNESS] = self.brightness
  File "/config/custom_components/teletask/light.py", line 76, in brightness
    int(self.device.current_brightness * 2.55) if self.device.supports_brightness else None
TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'

Any idea how to solve these?

**Comment by Tiemooowh** [comment]
Hey Tom,

Would you be able to add the config file you're using? (or a part of it at
least ;-))

Tnx
T

**Comment by tomdevos2401** [comment]
Hey T,

of course :)

tx already,
T

# Teletask
#teletask:
  host: 192.168.3.2
  port: 55957
  
  switch:
  - doip_component: flag
    address: "1"
    name: "TT_Home"
  - doip_component: flag
    address: "9"
    name: "TT_Slapen"
  - doip_component: flag
    address: "3"
    name: "TT_Poort"
  - doip_component: flag
    address: "4"
    name: "TT_Summer"
  - doip_component: flag
    address: "5"
    name: "TT_Autumn"
  - doip_component: flag
    address: "6"
    name: "TT_Winter"
  - doip_component: flag
    address: "7"
    name: "TT_Spring"
  - doip_component: locmood
    address: "11"
    name: "TT_locmood_Gordijnen"
  - doip_component: locmood
    address: "10"
    name: "TT_locmood_Zitplaats_Smooth"
  - doip_component: locmood
    address: "7"
    name: "TT_locmood_Keuken_Smooth"
  - doip_component: locmood
    address: "9"
    name: "TT_locmood_Bureau_Smooth"
  - doip_component: locmood
    address: "12"
    name: "TT_locmood_Boven_Smooth"
  - doip_component: locmood
    address: "29"
    name: "TT_locmood_Beneden_Smooth"
  - doip_component: genmood
    address: "1"
    name: "TT_genmood_Afsluiten"
  - doip_component: genmood
    address: "7"
    name: "TT_genmood_Opstaan"
  - doip_component: relay
    address: "16"
    name: "TT_relay_Poort"
  - doip_component: relay
    address: "5"
    name: "TT_relay_vloer_Zitplaats"
    
  light:
  - doip_component: relay
    address: "5"
    brightness_address: "4" 
    name: "TT_Zitplaats_Light"
  - doip_component: relay
    address: "6"
    brightness_address: "11" 
    name: "TT_Zitplaats_LED_kop"
  - doip_component: relay
    address: "6"
    brightness_address: "15" 
    name: "TT_Zitplaats_LED_zijkant"

**Comment by tomdevos2401** [comment]
hi T,

did you manage to find anything?

Thx,
T.

**Comment by Tiemooowh** [comment]
Hey Tom,

Did a patch yesterday, both of the PyTeletask module as of the Teletask
Component.
Unfortunately I ended up scratching my own environment due to a hardware
failure, so didn't get the chance to fully test it end to end.

I did do a check-in in Github, so normally the new version should also be
available to you.

Can you already do an re-evaluation?

Br
T

**Comment by tomdevos2401** [comment]
hey T,

will do, I'll keep you posted.
thanks for the great work!

T.

**Comment by tomdevos2401** [comment]
hi T,

I think I understand now what the problem is.

i configured a light as following. 5 is the output number of the dimmer, on autobus 5 with woutput 4

light:
  - doip_component: relay
    address: "5"
    brightness_address: "4" 
    name: "TT_Zitplaats_Light"

i also configured a relay as switch. 5 is the output number of the relay, on autobus 1 with address 1

switch:
  - doip_component: relay
    address: "5"
    name: "TT_relay_vloer_Zitplaats"

since this is two times address 5, although on different TT modules things get messed up.
do I do something wrong here? when I disable the light in the configuration everything (except for the light of course) is working just fine :)
