### ISSUE TITLE
Dimmers not working in lovelace default_view

### ISSUE THREAD

**Issue by LeGiGi** [Tiemooowh/homeassistant-teletask#7]
Hello T,

I have also installed the Teletask HACS integration.
All light (16 interfaces) on my Teletask PICOS Central Unit are integrated within Home Assistant. They are all listed on the Settings - Entities page and all added as enities to the lovelace/default_view UI.
The lights connected to the 4 dimmers do not work. They are added in the yaml file below switch and are not listed on the Settings - Entities page.

Can you please look at it and let me know how this can be resolved?

I am using the temporary Teletask "OPEN DOIP PROTOCOL" license.

![Teletask](https://user-images.githubusercontent.com/24864211/177616534-f1c89b6f-84bc-4534-aba9-0334284d8b12.JPG)

Below is my configuration.yaml export:

teletask:
  host: 192.168.0.5
  port: 55957

  switch:
  - doip_component: relay
    address: "1"
    brightness_address: "1"
    name: "Inkomhal"

  - doip_component: relay
    address: "2"
    brightness_address: "2"
    name: "Eettafel"

  - doip_component: relay
    address: "3"
    brightness_address: "3"
    name: "Zithoek"

  - doip_component: relay
    address: "4"
    brightness_address: "4"
    name: "Nachthal"

  light:
  - doip_component: relay
    address: "1"
    name: "Slaapkamer Amber"

  - doip_component: relay
    address: "2"
    name: "Berging"

  - doip_component: relay
    address: "3"
    name: "Keuken eiland"

  - doip_component: relay
    address: "4"
    name: "WC"

  - doip_component: relay
    address: "5"
    name: "Master bedroom plafond"

  - doip_component: relay
    address: "6"
    name: "Slaapkamer Yente"

  - doip_component: relay
    address: "7"
    name: "Dressing"

  - doip_component: relay
    address: "8"
    name: "Master bedroom make-up"

  - doip_component: relay
    address: "9"
    name: "Terras"

  - doip_component: relay
    address: "10"
    name: "Badkamer douche"

  - doip_component: relay
    address: "11"
    name: "Badkamer plafond"

  - doip_component: relay
    address: "12"
    name: "Master bedroom bed"

  - doip_component: relay
    address: "13"
    name: "sfeerlicht tv"

  - doip_component: relay
    address: "14"
    name: "sfeerlicht keuken"

  - doip_component: relay
    address: "15"
    name: "Keuken aanrecht"

  - doip_component: relay
    address: "16"
    name: "Badkamer spiegel"

Thank you,
Geert

**Comment by LeGiGi** [comment]
Anyone please?

**Comment by Tiemooowh** [comment]
Hey @LeGiGi ,

For 'brightness_address' to be used, you should define it as a 'light', not a 'switch'. (switches are not implementing brightness features.

However for the doip_component I'd opt for a 'flag' instead of a 'relay'.

Best regards,
Timo

**Comment by LeGiGi** [comment]
Hi Timo,

I changed the configuration.yaml according to your feedback. Restarted the home assistant a few times but still the same negative result.
Nothing happens when I hit the light button of the dimmer controlled lights on the lovelace/default_view UI.
Also the page "Instellingen - Apparaten & Diensten - Entiteiten" has the manually added lights on a dimmer but it seems they are not automatically detected.

Here is my updated configuration.yaml:

teletask:
  host: 192.168.0.5
  port: 55957

  light:
  - doip_component: flag
    address: "1"
    brightness_address: "20"
    name: "Inkomhal"

  - doip_component: flag
    address: "2"
    brightness_address: "20"
    name: "Eettafel"

  - doip_component: flag
    address: "3"
    brightness_address: "20"
    name: "Zithoek"

  - doip_component: flag
    address: "4"
    brightness_address: "20"
    name: "Nachthal"

  - doip_component: relay
    address: "1"
    name: "Slaapkamer Amber"

  - doip_component: relay
    address: "2"
    name: "Berging"

  - doip_component: relay
    address: "3"
    name: "Keuken eiland"

  - doip_component: relay
    address: "4"
    name: "WC"

  - doip_component: relay
    address: "5"
    name: "Master bedroom plafond"

  - doip_component: relay
    address: "6"
    name: "Slaapkamer Yente"

  - doip_component: relay
    address: "7"
    name: "Dressing"

  - doip_component: relay
    address: "8"
    name: "Master bedroom make-up"

  - doip_component: relay
    address: "9"
    name: "Terras"

  - doip_component: relay
    address: "10"
    name: "Badkamer douche"

  - doip_component: relay
    address: "11"
    name: "Badkamer plafond"

  - doip_component: relay
    address: "12"
    name: "Master bedroom bed"

  - doip_component: relay
    address: "13"
    name: "sfeerlicht tv"

  - doip_component: relay
    address: "14"
    name: "sfeerlicht keuken"

  - doip_component: relay
    address: "15"
    name: "Keuken aanrecht"

  - doip_component: relay
    address: "16"
    name: "Badkamer spiegel"

**Comment by Tiemooowh** [comment]
Hey Geert,

In your configuration Inkomhal, Eettafel, Nachthal, ... are all using the
same dimmer at dimmer port 20?

In my config
    - doip_component: relay
      address: "30"
      brightness_address: "1"
      name: Slaapkamer 3 - LED-strip

In my setup:
[image: image.png]
[image: image.png]

In the UI
[image: image.png]
[image: image.png]

Regards
T

**Comment by LeGiGi** [comment]
Hi Timo,

kinda confused now, is the brightness_address the dimmer brightness value or its address seen by Teletask controller?
Why are there the address and the brightness_address? Please clarify…
So I used flag instead of relay for the dimmer lights.

It does not work, nothing found/detected.

I still have the below config set with my Teletask dimmer lights
teletask:
host: 192.168.0.5
port: 55957

light:

doip_component: flag
address: "1"
brightness_address: "20"
name: "Inkomhal"

doip_component: flag
address: "2"
brightness_address: "20"
name: "Eettafel"

doip_component: flag
address: "3"
brightness_address: "20"
name: "Zithoek"

doip_component: flag
address: "4"
brightness_address: "20"
name: "Nachthal"

doip_component: relay
address: "1"
name: "Slaapkamer Amber"

**Comment by LeGiGi** [comment]
Hi Timo,

The images you tried to share 3 days ago are not visible.

Regards,
Geert

Outlook voor iOS<https://aka.ms/o0ukef> downloaden
________________________________
Van: Tiemooowh ***@***.***>
Verzonden: Wednesday, July 20, 2022 6:43:45 PM
Aan: Tiemooowh/homeassistant-teletask ***@***.***>
CC: LeGiGi ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [Tiemooowh/homeassistant-teletask] Dimmers not working in lovelace default_view (Issue #7)


Hey Geert,

In your configuration Inkomhal, Eettafel, Nachthal, ... are all using the
same dimmer at dimmer port 20?

In my config
- doip_component: relay
address: "30"
brightness_address: "1"
name: Slaapkamer 3 - LED-strip

In my setup:
[image: image.png]
[image: image.png]

In the UI
[image: image.png]
[image: image.png]

Regards
T

**Comment by LeGiGi** [comment]
Hi Timo,

The images you tried to share 3 days ago are not visible.

Regards,
Geert

**Comment by LeGiGi** [comment]
Hi Timo,

kinda confused now, is the brightness_address the dimmer brightness value or its address seen by Teletask controller?
Why are there the address and the brightness_address? Please clarify…
So I used flag instead of relay for the dimmer lights.

It does not work, nothing found/detected.

I still have the below config set with my Teletask dimmer lights
teletask:
host: 192.168.0.5
port: 55957

light:

doip_component: flag
address: "1"
brightness_address: "20"
name: "Inkomhal"

doip_component: flag
address: "2"
brightness_address: "20"
name: "Eettafel"

doip_component: flag
address: "3"
brightness_address: "20"
name: "Zithoek"

doip_component: flag
address: "4"
brightness_address: "20"
name: "Nachthal"

doip_component: relay
address: "1"
name: "Slaapkamer Amber"

**Comment by Tiemooowh** [comment]
Hey Geert,

In your configuration Inkomhal, Eettafel, Nachthal, ... are all using the same dimmer at dimmer port 20? 

In my config
    - doip_component: relay
      address: "30"
      brightness_address: "1"
      name: Slaapkamer 3 - LED-strip

In my setup:
<img width="851" alt="image" src="https://user-images.githubusercontent.com/12693421/180636144-e3411ef2-bd43-4a5f-bc7f-2ed1b3b60481.png">
![image2](https://user-images.githubusercontent.com/12693421/180636145-5681c970-8d52-49e0-9f96-7ffdebc6539a.png)

In the UI
<img width="384" alt="image3" src="https://user-images.githubusercontent.com/12693421/180636150-6124e808-f9a4-4c9a-b601-9b6d86646101.png">
<img width="565" alt="image4" src="https://user-images.githubusercontent.com/12693421/180636151-d349d579-cedc-42bd-8b10-0dc56d6cf303.png">


Regards
T

**Comment by Tiemooowh** [comment]
Hey Geert,

One of the things my electrician mentioned was separating on/off from
dimmer values.
I understand that you have lights that are only attached to the dimmer,
without controlling it via an on/off relay then?

Hence the 'work around' with a flag.. where you create a 'fake' on/off for
the light (you should do this for every light).
The brightness address then is the dimmer address in Teletask.

Br
T

**Comment by LeGiGi** [comment]
Hi Timo,

I changed the configuration.yaml according to your feedback. Restarted the home assistant a few times but still the same negative result.
Nothing happens when I hit the light button of the dimmer controlled lights on the lovelace/default_view UI.
Also the page "Instellingen - Apparaten & Diensten - Entiteiten" has the manually added lights on a dimmer but it seems they are not automatically detected.

Here is my updated configuration.yaml:

teletask:
  host: 192.168.0.5
  port: 55957

  light:
  - doip_component: flag
    address: "1"
    brightness_address: "20"
    name: "Inkomhal"

  - doip_component: flag
    address: "2"
    brightness_address: "20"
    name: "Eettafel"

  - doip_component: flag
    address: "3"
    brightness_address: "20"
    name: "Zithoek"

  - doip_component: flag
    address: "4"
    brightness_address: "20"
    name: "Nachthal"

  - doip_component: relay
    address: "1"
    name: "Slaapkamer Amber"

  - doip_component: relay
    address: "2"
    name: "Berging"

  - doip_component: relay
    address: "3"
    name: "Keuken eiland"

  - doip_component: relay
    address: "4"
    name: "WC"

  - doip_component: relay
    address: "5"
    name: "Master bedroom plafond"

  - doip_component: relay
    address: "6"
    name: "Slaapkamer Yente"

  - doip_component: relay
    address: "7"
    name: "Dressing"

  - doip_component: relay
    address: "8"
    name: "Master bedroom make-up"

  - doip_component: relay
    address: "9"
    name: "Terras"

  - doip_component: relay
    address: "10"
    name: "Badkamer douche"

  - doip_component: relay
    address: "11"
    name: "Badkamer plafond"

  - doip_component: relay
    address: "12"
    name: "Master bedroom bed"

  - doip_component: relay
    address: "13"
    name: "sfeerlicht tv"

  - doip_component: relay
    address: "14"
    name: "sfeerlicht keuken"

  - doip_component: relay
    address: "15"
    name: "Keuken aanrecht"

  - doip_component: relay
    address: "16"
    name: "Badkamer spiegel"


Can you troubleshoot please?

Thank you,
Geert

________________________________
Van: Tiemooowh ***@***.***>
Verzonden: dinsdag 19 juli 2022 15:51
Aan: Tiemooowh/homeassistant-teletask ***@***.***>
CC: LeGiGi ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [Tiemooowh/homeassistant-teletask] Dimmers not working in lovelace default_view (Issue #7)


Hey @LeGiGi<https://github.com/LeGiGi> ,

For 'brightness_address' to be used, you should define it as a 'light', not a 'switch'. (switches are not implementing brightness features.

However for the doip_component I'd opt for a 'flag' instead of a 'relay'.

Best regards,
Timo

**Comment by Tiemooowh** [comment]
Hey Geert,

I'm no longer capable of debugging/troubleshooting the Teletask module,
since I don't have access to the Teletask Unit I was using to develop this.
If somebody else would want to stand up to do it, please let me know.

Best regards
Timo

**Comment by LtPixel** [comment]
Hey  @LeGiGi 

Let me share how I've manage to get this to work...

1. In Teletaks, I first created a "flag" for the dimmeable spots in my dining room.

   + FLG 05 Dining Room Spots

2. In Teletaks, I then create a "process Function" to monitor the flag. This is basically tellinging Teletask, to take some action if the flag would change state.

   + PRS 07 Dining Room Spots
       + funtion to be monitored: FLG 05 Dining Room Spots > On
       + function to be executed: DIM 02 Dining Room Spots > 100% / Off
       + options
            + operation if activated: ON if True & OFF if FALSE (all edges)
            + deactivate handling: when process function is de-actvate: don't change outut

Note: If you don't implement this, turning the dimmer lights on, won't do anything. You would only be able to change the brightness... where brightness 0, doesn't turn off the light.

3. In Teletask, you need to make sure this process function starts when Teletask starts. In the menu, go to "Extras", then "Options". I the "Option" tab, under the "Service Options" section, add an "Auto Start Function" which enables the process function.

   + auto start function: (Local Mood) LMD 12 Autostart
      + select "Process function",  PRS 07 Dining Room Spots

Note: If the process function is not running, Teletask will not monitor the flag. The first time I created a process function, I wrongly had the assumption that it would simply be running. In the Teletask diagnostics, I noticed I could turn this process function on and off.

4. In my "configuration.yaml" file, I have the following config for my dimmed spots: 

   teletask:
     host: 192.168.1.51
     port: 55957
     light:
       - doip_component: flag
         address: "5"
         brightness_address: "2"
         name: "Dining Room Teletask Spots"

Notes:
* I first made the stupid mistake by placing the lights under the "switch:" section. That dosn't work, as your lights will be recognised as switches in Home Assistant. 
* The "address" in this case, is the address of the flag. As I'm manipulating "FLG 05 (Dining Room Spots)", this needs to be "5".
* The "brightness_address" is NOT the brightness level. It is the address of the dimmer. As I'm trying to control "DIM 02 (Dining Room Spots)", this needs to be "2".

That's all. I hop this helps. If you have additional questions, feel free to let me know.

Regards, Peter

**Comment by LeGiGi** [comment]
Hi Peter,

Some background about the Teletask PICOS module and the dimmers.
The electrician did install 4 individual NIKO 330-00701 modules (each 1 DIN size) that are connected to the dimmer inputs on the PICOS.
Each dimmer has its own light/light group

Here below a screenshot how its reflects on the Teletask PICOS.

[cid:77bd058d-9ff8-485e-9557-c4d8beb75dbe]

What is the correct address if you look at the above screenshot?


Thank you,
LeGiGi (Geert)
________________________________
Van: LtPixel ***@***.***>
Verzonden: zondag 15 januari 2023 12:09
Aan: Tiemooowh/homeassistant-teletask ***@***.***>
CC: LeGiGi ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [Tiemooowh/homeassistant-teletask] Dimmers not working in lovelace default_view (Issue #7)


Hey @LeGiGi<https://github.com/LeGiGi>

Let me share how I've manage to get this to work...

  1.  In Teletaks, I first created a "flag" for the dimmeable spots in my dining room.

     *   FLG 05 Dining Room Spots
  2.  In Teletaks, I then create a "process Function" to monitor the flag. This is basically tellinging Teletask, to take some action if the flag would change state.

     *   PRS 07 Dining Room Spots
        *   funtion to be monitored: FLG 05 Dining Room Spots > On
        *   function to be executed: DIM 02 Dining Room Spots > 100% / Off
        *   options
           *   operation if activated: ON if True & OFF if FALSE (all edges)
           *   deactivate handling: when process function is de-actvate: don't change outut

Note: If you don't implement this, turning the dimmer lights on, won't do anything. You would only be able to change the brightness... where brightness 0, doesn't turn off the light.

  1.  In Teletask, you need to make sure this process function starts when Teletask starts. In the menu, go to "Extras", then "Options". I the "Option" tab, under the "Service Options" section, add an "Auto Start Function" which enables the process function.

     *   auto start function: (Local Mood) LMD 12 Autostart
        *   select "Process function", PRS 07 Dining Room Spots

Note: If the process function is not running, Teletask will not monitor the flag. The first time I created a process function, I wrongly had the assumption that it would simply be running. In the Teletask diagnostics, I noticed I could turn this process function on and off.

  1.  In my "configuration.yaml" file, I have the following config for my dimmed spots:

teletask:
host: 192.168.1.51
port: 55957
light:
- doip_component: flag
address: "5"
brightness_address: "2"
name: "Dining Room Teletask Spots"

Notes:

  *   I first made the stupid mistake by placing the lights under the "switch:" section. That dosn't work, as your lights will be recognised as switches in Home Assistant.
  *   The "address" in this case, is the address of the flag. As I'm manipulating "FLG 05 (Dining Room Spots)", this needs to be "5".
  *   The "brightness_address" is NOT the brightness level. It is the address of the dimmer. As I'm trying to control "DIM 02 (Dining Room Spots)", this needs to be "2".

That's all. I hop this helps. If you have additional questions, feel free to let me know.

Regards, Peter

**Comment by LtPixel** [comment]
I don't see the screenshot. Can you upload it here? https://github.com/Tiemooowh/homeassistant-teletask/issues/7

**Comment by LeGiGi** [comment]
![DIMMERS screenshot](https://user-images.githubusercontent.com/24864211/212542099-c2565be1-0834-4342-990d-a8b09120241f.JPG)

**Comment by LtPixel** [comment]
Geert,

It should be like this...

light:
  - doip_component: flag
    address: "1"
    brightness_address: "1"
    name: "Inkomhal Verlichting Voordeur"

  - doip_component: flag
    address: "2"
    brightness_address: "2"
    name: "Woonruimte Verlichting Tafel"

  - doip_component: flag
    address: "3"
    brightness_address: "3"
    name: "Woonruimte Verlichting Zithoek"

  - doip_component: flag
    address: "4"
    brightness_address: "4"
    name: "Inkomhal Verlichting Gang"

I am making the assumption here that you created 4 flags in Teletask:
  + FLG 01 Inkomhal Verlichting Voordeur
  + FLG 02 Woonruimte Verlichting Tafel
  + FLG 03 Woonruimte Verlichting Zithoek
  + FLG 04 Inkomhal Verlichting Gang

This will create 4 entties in Home Assistant:
  + light.inkomhal_verlichting_voordeur
  + light.woonruimte_verlichting_vafel
  + light.woonruimte_verlichting_zithoek
  + light.inkomhal_verlichting_gang

If you asign any of these to a "Light" card, you will be able to control them.

The next (and final) step is to set up the process function in Teletask as I mentioned in my previous post.

Regards,

Peter

**Comment by LeGiGi** [comment]
Hi Peter.

Got it to work! I see the new entities in HA, the Light card is working with a type "custom:slider-entity-row".
Cool, works great.

Thank you so much.

**Comment by LtPixel** [comment]
Top! 👍I'm very happy to read this.

✅ @Tiemooowh You can close this issue. 😉

**Comment by Tiemooowh** [comment]
Good to hear that!
