### ISSUE TITLE
missing unique_id

### ISSUE THREAD

**Issue by dsmagghe** [Tiemooowh/homeassistant-teletask#8]
Hi,

is there a way to get a unique_id into the entities?
Having +100 lights would like to edit them in HA to have areas, but since there is no unique_id I am not able to modify or edit areas to be able to group some lights.

**Comment by LtPixel** [comment]
Hey @Tiemooowh 

Why don't you simply add an optional "unique_id" key to the config? I've noticed that other integration in Home Assistant do exactly the same thing.

teletask:
  host: 192.168.1.1
  port: 55957

  switch:
  - doip_component: relay
    address: "1"
    name: "Electrical Socket Carport"
    unique_id: "8a2ede8e-945b-11ed-a1eb-0242ac120002"

In "def __init__(self, device)" of "light.py" and "switch.py", you would simply have to add one line...

   self._attr_unique_id = config.get("unique_id")

**Comment by LtPixel** [comment]
You could also make a combination of the .name, .doip_component and .group_address_switch. 

In "def init(self, device)" of "light.py" and "switch.py", adding the following line:

        """ Define a unique id for the entity. """
        self._attr_unique_id = (device.name + device.doip_component + device.group_address_switch).replace(" ", "")

**Comment by LtPixel** [comment]
Hey @Tiemooowh , (and @dsmagghe )

I made the following change in my setup...
In both "light.py", under "def __init__(self, device)", I added line 47: 
In "switch.py", under "def __init__(self, device)", I added line 43: 

   `self._attr_unique_id = ("teletask_" + device.doip_component + "_" + device.name).lower().replace(" ", "_")`

I don't have any means to debug this; not entirely sure of "device.doip_component" and "device.name" are already initialize in this function. It does however work in Home Assistant. The lights don't complain that they are missing a unique_id, and I can assign them to my area's.

Regards,

Peter

**Comment by Tiemooowh** [comment]
Hey @LtPixel  and @dsmagghe 

At this point in time I'm unable to do development since I have no validation environment (had to leave the house with Teletask Installation for personal reasons).

@LtPixel  I've invited you as a contributor to this repo, so if you do see yourself fit to maintain it in the mean time, please feel free to do so!

(also feel free to directly reach out to me at timothy.de.mey <at> gmail.com) ;-)

Warm regards
Timo

**Comment by LtPixel** [comment]
@Tiemooowh @dsmagghe 

I've created an update to address this issue.

By introducing the use of a "unique_id" in the configuration file. _* I've noticed that this seems like a common practise in HA (alsu using it in my HA groups)._ 

This change ensures the entities can be configured in HA; setting an icon, assigning them to a room, and even renaming them in the config file.

For example...

```
host: 192.168.1.101
port: 55957

switch:

  - doip_component: relay
    address: "1"
    name: "Office Teletask Plug"
    unique_id: 4cf2ee7a-a3e2-11ed-a8fc-0242ac120002

light:

  - doip_component: relay
    address: "2"
    name: "Office Teletask Spots"
    unique_id: 54e3a6ec-a3e2-11ed-a8fc-0242ac120002
```

I've generated a (unique) guid for all my switches and lights, but you can basiaclly use any unique identifier. _* I've used the online generator: https://www.uuidgenerator.net/version1_

This configuration is running all my Teletask lights and switches.
